services:
  - type: web
    name: answer-evaluator
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile
    dockerContext: .

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: JWT_SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        value: sqlite:///app.db